brace_style = "AlwaysNextLine"
chain_width = 1
control_brace_style = "AlwaysNextLine"
end_of_line = "crlf"
fn_call_width = 80
hard_tabs = true
indent_style = "Block"
max_width = 120
struct_lit_width = 40
